import { defineSource, type SourceDefinition } from "../domain.js";

export const AI_AND_SOFTWARE_SOURCES: SourceDefinition[] = [
  defineSource({
    id: "interconnects",
    slug: "interconnects-ai",
    name: "Interconnects AI",
    category: "ai",
    ingestion: { kind: "feed", url: "https://www.interconnects.ai/feed" },
  }),
  defineSource({
    id: "import-ai",
    slug: "import-ai",
    name: "Import AI",
    category: "ai",
    ingestion: { kind: "feed", url: "https://importai.substack.com/feed" },
  }),
  defineSource({
    id: "latent-space",
    slug: "latent-space",
    name: "Latent Space",
    category: "ai",
    ingestion: { kind: "feed", url: "https://www.latent.space/feed" },
  }),
  defineSource({
    id: "ahead-of-ai",
    slug: "ahead-of-ai",
    name: "Ahead of AI",
    category: "ai",
    ingestion: { kind: "feed", url: "https://magazine.sebastianraschka.com/feed" },
  }),
  defineSource({
    id: "ai-normal-technology",
    slug: "ai-as-normal-technology",
    name: "AI as Normal Technology",
    category: "ai",
    ingestion: { kind: "feed", url: "https://www.aisnakeoil.com/feed" },
  }),
  defineSource({
    id: "one-useful-thing",
    slug: "one-useful-thing",
    name: "One Useful Thing",
    category: "ai",
    ingestion: { kind: "feed", url: "https://www.oneusefulthing.org/feed" },
  }),
  defineSource({
    id: "last-week-in-ai",
    slug: "last-week-in-ai",
    name: "Last Week in AI",
    category: "ai",
    ingestion: { kind: "feed", url: "https://lastweekin.ai/feed" },
  }),
  defineSource({
    id: "simon-willison",
    slug: "simon-willisons-weblog",
    name: "Simon Willison's Weblog",
    category: "software",
    ingestion: { kind: "feed", url: "https://simonwillison.net/atom/entries/" },
  }),
  defineSource({
    id: "chip-huyen",
    slug: "chip-huyen",
    name: "Chip Huyen",
    category: "ai",
    ingestion: { kind: "feed", url: "https://huyenchip.com/feed.xml" },
  }),
  defineSource({
    id: "lil-log",
    slug: "lil-log",
    name: "Lil'Log",
    category: "ai",
    ingestion: { kind: "feed", url: "https://lilianweng.github.io/lil-log/feed.xml" },
  }),
  defineSource({
    id: "the-gradient",
    slug: "the-gradient",
    name: "The Gradient",
    category: "ai",
    ingestion: { kind: "feed", url: "https://thegradient.pub/rss/" },
  }),
  defineSource({
    id: "openai-news",
    slug: "openai-news",
    name: "OpenAI News",
    category: "ai",
    ingestion: { kind: "feed", url: "https://openai.com/news/rss.xml" },
  }),
  defineSource({
    id: "google-deepmind",
    slug: "google-deepmind-news",
    name: "Google DeepMind News",
    category: "ai",
    ingestion: { kind: "feed", url: "https://deepmind.google/blog/rss.xml" },
  }),
  defineSource({
    id: "google-research",
    slug: "google-research",
    name: "Google Research",
    category: "ai",
    ingestion: { kind: "feed", url: "https://research.google/blog/rss/" },
  }),
  defineSource({
    id: "hugging-face",
    slug: "hugging-face-blog",
    name: "Hugging Face Blog",
    category: "ai",
    ingestion: { kind: "feed", url: "https://huggingface.co/blog/feed.xml" },
  }),
  defineSource({
    id: "pragmatic-engineer",
    slug: "the-pragmatic-engineer",
    name: "The Pragmatic Engineer",
    category: "software",
    ingestion: { kind: "feed", url: "https://newsletter.pragmaticengineer.com/feed" },
  }),
  defineSource({
    id: "bytebytego",
    slug: "bytebytego-newsletter",
    name: "ByteByteGo Newsletter",
    category: "software",
    ingestion: { kind: "feed", url: "https://blog.bytebytego.com/feed" },
  }),
  defineSource({
    id: "martin-fowler",
    slug: "martin-fowler",
    name: "Martin Fowler",
    category: "software",
    ingestion: { kind: "feed", url: "https://martinfowler.com/feed.atom" },
  }),
  defineSource({
    id: "github-engineering",
    slug: "github-engineering",
    name: "GitHub Engineering",
    category: "software",
    ingestion: { kind: "feed", url: "https://github.blog/engineering/feed/" },
  }),
  defineSource({
    id: "cloudflare-workers-ai",
    slug: "cloudflare-workers-ai",
    name: "Cloudflare Workers AI",
    category: "software",
    ingestion: { kind: "feed", url: "https://blog.cloudflare.com/tag/workers-ai/rss/" },
  }),
  defineSource({
    id: "dropbox-tech",
    slug: "dropbox-tech-blog",
    name: "Dropbox Tech Blog",
    category: "software",
    ingestion: { kind: "feed", url: "https://dropbox.tech/feed" },
  }),
  defineSource({
    id: "netflix-techblog",
    slug: "netflix-techblog",
    name: "Netflix TechBlog",
    category: "software",
    ingestion: { kind: "feed", url: "https://netflixtechblog.com/feed" },
  }),
  defineSource({
    id: "meta-engineering",
    slug: "meta-engineering",
    name: "Meta Engineering",
    category: "software",
    ingestion: { kind: "feed", url: "https://engineering.fb.com/feed/" },
  }),
  defineSource({
    id: "aws-architecture",
    slug: "aws-architecture-blog",
    name: "AWS Architecture Blog",
    category: "software",
    ingestion: { kind: "feed", url: "https://aws.amazon.com/blogs/architecture/feed/" },
  }),
];
