import { defineSource, type SourceDefinition } from "../domain.js";

export const GAMING_SOURCES: SourceDefinition[] = [
  defineSource({
    id: "hacker-news-best",
    slug: "hacker-news-best",
    name: "Hacker News: Best",
    category: "software",
    ingestion: {
      kind: "hacker-news",
      url: "https://hacker-news.firebaseio.com/v0/beststories.json",
    },
  }),
  defineSource({
    id: "game-informer-features",
    slug: "game-informer-features",
    name: "Game Informer Features",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://gameinformer.com/features.xml" },
  }),
  defineSource({
    id: "game-informer-previews",
    slug: "game-informer-previews",
    name: "Game Informer Previews",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://gameinformer.com/previews.xml" },
  }),
  defineSource({
    id: "game-informer-reviews",
    slug: "game-informer-reviews",
    name: "Game Informer Reviews",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://gameinformer.com/reviews.xml" },
  }),
  defineSource({
    id: "game-file",
    slug: "game-file",
    name: "Game File",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://www.gamefile.news/feed" },
  }),
  defineSource({
    id: "remap",
    slug: "remap",
    name: "Remap",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://remapradio.com/rss/" },
  }),
  defineSource({
    id: "game-developer",
    slug: "game-developer",
    name: "Game Developer",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://www.gamedeveloper.com/rss.xml" },
  }),
  defineSource({
    id: "gamediscoverco",
    slug: "gamediscoverco",
    name: "GameDiscoverCo",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://newsletter.gamediscover.co/feed" },
  }),
  defineSource({
    id: "how-to-market-a-game",
    slug: "how-to-market-a-game",
    name: "How To Market A Game",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://howtomarketagame.com/feed/" },
  }),
  defineSource({
    id: "indie-dev-monday",
    slug: "indie-dev-monday",
    name: "Indie Dev Monday",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://indiedevmonday.com/feed.xml" },
  }),
  defineSource({
    id: "indie-games-plus",
    slug: "indie-games-plus",
    name: "Indie Games Plus",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://indiegamesplus.com/feed/" },
  }),
  defineSource({
    id: "gamedev-reports",
    slug: "gamedev-reports",
    name: "GameDev Reports",
    category: "gaming",
    ingestion: { kind: "autodiscover", url: "https://gamedevreports.substack.com/" },
  }),
  defineSource({
    id: "game-from-scratch",
    slug: "gamefromscratch",
    name: "GameFromScratch",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://gamefromscratch.com/feed/" },
  }),
  defineSource({
    id: "ai-and-games",
    slug: "ai-and-games",
    name: "AI and Games",
    category: "gaming",
    ingestion: { kind: "autodiscover", url: "https://www.aiandgames.com/" },
  }),
  defineSource({
    id: "video-game-history-foundation",
    slug: "video-game-history-foundation",
    name: "Video Game History Foundation",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://gamehistory.org/feed/" },
  }),
  defineSource({
    id: "gamemaker-blog",
    slug: "gamemaker-blog",
    name: "GameMaker Blog",
    category: "gaming",
    ingestion: { kind: "feed", url: "https://gamemaker.io/en/blog/rss" },
  }),
];
