import { defineSource, type SourceDefinition } from "../domain.js";

export const VISUAL_AND_HARDWARE_SOURCES: SourceDefinition[] = [
  defineSource({
    id: "graphics-programming-weekly",
    slug: "graphics-programming-weekly",
    name: "Graphics Programming Weekly — Jendrik Illner",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://www.jendrikillner.com/index.xml" },
  }),
  defineSource({
    id: "acm-siggraph",
    slug: "acm-siggraph-blog",
    name: "ACM SIGGRAPH Blog",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://blog.siggraph.org/feed/" },
  }),
  defineSource({
    id: "nvidia-graphics",
    slug: "nvidia-graphics-rendering",
    name: "NVIDIA Technical Blog — Graphics / Rendering",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://developer.nvidia.com/blog/category/graphics/feed/" },
  }),
  defineSource({
    id: "nvidia-robotics",
    slug: "nvidia-robotics",
    name: "NVIDIA Technical Blog — Robotics",
    category: "robotics",
    ingestion: { kind: "feed", url: "https://developer.nvidia.com/blog/category/robotics/feed/" },
  }),
  defineSource({
    id: "amd-gpuopen",
    slug: "amd-gpuopen",
    name: "AMD GPUOpen",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://gpuopen.com/feed/" },
  }),
  defineSource({
    id: "fxguide",
    slug: "fxguide",
    name: "fxguide",
    category: "vfx",
    ingestion: { kind: "feed", url: "https://fxguide.com/rss" },
  }),
  defineSource({
    id: "semianalysis",
    slug: "semianalysis",
    name: "SemiAnalysis",
    category: "hardware",
    ingestion: { kind: "feed", url: "https://newsletter.semianalysis.com/feed" },
  }),
  defineSource({
    id: "chips-and-cheese",
    slug: "chips-and-cheese",
    name: "Chips and Cheese",
    category: "hardware",
    ingestion: { kind: "feed", url: "https://chipsandcheese.com/feed" },
  }),
  defineSource({
    id: "ars-features",
    slug: "ars-technica-features",
    name: "Ars Technica Features",
    category: "hardware",
    ingestion: { kind: "feed", url: "https://feeds.arstechnica.com/arstechnica/features" },
  }),
  defineSource({
    id: "jeff-geerling",
    slug: "jeff-geerling",
    name: "Jeff Geerling",
    category: "hardware",
    ingestion: { kind: "feed", url: "https://www.jeffgeerling.com/blog.xml" },
  }),
  defineSource({
    id: "unreal-engine",
    slug: "unreal-engine",
    name: "Unreal Engine",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://www.unrealengine.com/rss?lang=en-US" },
  }),
  defineSource({
    id: "cg-channel",
    slug: "cg-channel",
    name: "CG Channel",
    category: "vfx",
    ingestion: { kind: "feed", url: "https://feeds2.feedburner.com/cgchannel/nHpU" },
  }),
  defineSource({
    id: "khronos-blog",
    slug: "khronos-blog",
    name: "Khronos Blog",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://www.khronos.org/feeds/blog_feed" },
  }),
  defineSource({
    id: "khronos-vulkan-news",
    slug: "khronos-vulkan-news",
    name: "Khronos Vulkan News",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://www.khronos.org/feeds/vulkan_news_feed" },
  }),
  defineSource({
    id: "jcgt",
    slug: "journal-of-computer-graphics-techniques",
    name: "Journal of Computer Graphics Techniques",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://jcgt.org/feed.xml" },
  }),
  defineSource({
    id: "alliance-openusd",
    slug: "alliance-for-openusd",
    name: "Alliance for OpenUSD",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://aousd.org/feed/" },
  }),
  defineSource({
    id: "aswf",
    slug: "academy-software-foundation",
    name: "Academy Software Foundation",
    category: "vfx",
    ingestion: { kind: "feed", url: "https://www.aswf.io/feed/" },
  }),
  defineSource({
    id: "eurographics",
    slug: "eurographics",
    name: "Eurographics",
    category: "graphics",
    ingestion: { kind: "feed", url: "https://www.eg.org/wp/feed/" },
  }),
];
